version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'   ## 镜像
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"                 ## 对外暴露的端口号
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'       ## 镜像
    container_name: kafka
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime ## 挂载位置（kafka镜像和宿主机器之间时间保持一直）
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      # 10.1.76.224 替换为你机器的ip，不能用127.0.0.1
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.1.76.224:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # 允许使用PLAINTEXT协议(镜像中默认为关闭,需要手动开启)
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 关闭自动创建 topic 功能
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      # 全局消息过期时间 6 小时(测试时可以设置短一点)
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
    depends_on:
      - zookeeper
  kafka-manager:
    image: 'hlebalbau/kafka-manager:latest'                ## 镜像：开源的web管理kafka集群的界面
    restart: always
    container_name: kafka-manager
    environment:
      ZK_HOSTS: 10.1.76.224                  ## 修改:宿主机IP
      APPLICATION_SECRET: letmein
    ports:
      - "9000:9000"                               ## 暴露端口
    depends_on:
      - zookeeper
      - kafka
