version: '3'
services:
  zookeeper1:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  zookeeper2:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper2
    ports:
      - "2182:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  zookeeper3:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper3
    ports:
      - "2183:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    image: bitnami/kafka:2.8.1
    ports:
      - "9092:9092"
    environment:
      # 192.168.31.19 替换为你机器的ip，不能用127.0.0.1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.31.19
      KAFKA_CREATE_TOPICS: TestComposeTopic:4:3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_BROKER_ID: 1
      # 192.168.31.19 替换为你机器的ip，不能用127.0.0.1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.31.19:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    container_name: kafka1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: bitnami/kafka:2.8.1
    ports:
      - "9093:9093"
    environment:
      # 192.168.31.19 替换为你机器的ip，不能用127.0.0.1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.31.19
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_BROKER_ID: 2
      # 192.168.31.19 替换为你机器的ip，不能用127.0.0.1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.31.19:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    container_name: kafka2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka3:
    image: bitnami/kafka:2.8.1
    ports:
      - "9094:9094"
    environment:
      # 192.168.31.19 替换为你机器的ip，不能用127.0.0.1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.31.19
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_BROKER_ID: 3
      # 192.168.31.19 替换为你机器的ip，不能用127.0.0.1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.31.19:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    container_name: kafka3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka1:9092,kafka2:9093,kafka3:9094
